export const menuActionTypes = {
    SET_CHECKED_MENUES: 'SET_CHECKED_MENUES',
    SET_CART_LIST: 'SET_CART_LIST',
    ORDER_COMPLETE: 'ORDER_COMPLETE',
    SET_TOTAL_PRICE: 'SET_TOTAL_PRICE',
    SET_SELECTED_COUPON: 'SET_SELECTED_COUPON',
    SET_INITIALIZE_STATE: 'SET_INITIALIZE_STATE'
}